/**
 * Seed: /src/agent-mount.tsx — Runtime shell / immune layer.
 *
 * Provides:
 * - AgentErrorBoundary — catches agent crashes
 * - AgentToolbar — persistent think/evolve FAB (cannot be evolved away)
 * - AgentMount — wires state, self, and agent body together
 * - AgentProps, AgentSelf, ThinkResult type re-exports
 */

const L: string[] = [];
const o = (s: string) => L.push(s);

o('import React, { Component, useCallback } from "react";');
o('import { useAgentState, useAgentSelf } from "./useAgentState";');
o('import type { AgentSelf, ThinkResult } from "./useAgentState";');
o('');
o('export type { AgentSelf, ThinkResult };');
o('');
o('class AgentErrorBoundary extends Component<');
o('  { children: React.ReactNode; onError?: (error: Error) => void },');
o('  { hasError: boolean; error: Error | null }');
o('> {');
o('  state = { hasError: false, error: null };');
o('  static getDerivedStateFromError(error: Error) { return { hasError: true, error }; }');
o('  componentDidCatch(error: Error, info: React.ErrorInfo) {');
o('    console.error("[agent-mount] Agent body crashed:", error, info);');
o('    this.props.onError?.(error);');
o('  }');
o('  render() {');
o('    if (this.state.hasError) {');
o('      return (');
o('        <div style={{ padding: 16, background: "#fff0f0", border: "1px solid #ff9a9a", borderRadius: 8 }}>');
o('          <h3 style={{ margin: 0, color: "#c00" }}>Agent Error</h3>');
o('          <pre style={{ margin: "8px 0 0", fontSize: 12, whiteSpace: "pre-wrap" }}>');
o('            {this.state.error?.message}');
o('          </pre>');
o('          <button onClick={() => this.setState({ hasError: false, error: null })} style={{ marginTop: 8, padding: "4px 12px" }}>Retry</button>');
o('        </div>');
o('      );');
o('    }');
o('    return this.props.children;');
o('  }');
o('}');
o('');
o('export interface AgentProps {');
o('  state: Record<string, any>;');
o('  act: (patch: Record<string, any>) => void;');
o('  self: AgentSelf;');
o('}');
o('');
o('function AgentToolbar({ self, act }: { self: AgentSelf; act: (patch: Record<string, any>) => void }) {');
o('  const [isOpen, setIsOpen] = React.useState(false);');
o('  const [input, setInput] = React.useState("");');
o('  const [lastResponse, setLastResponse] = React.useState<string | null>(null);');
o('  const busy = self.isThinking || self.isEvolving;');
o('');
o('  const handleThink = async () => {');
o('    if (!input.trim() || busy) return;');
o('    const prompt = input.trim();');
o('    setInput("");');
o('    setLastResponse("...");');
o('    const result = await self.think(prompt);');
o('    setLastResponse(result.content || JSON.stringify(result));');
o('    if (result.actions) { for (const action of result.actions) act(action); }');
o('    if (result.shouldEvolve && result.evolveReason) {');
o('      setLastResponse(prev => (prev || "") + "\\n\\u21bb " + result.evolveReason);');
o('      await self.evolve(result.evolveReason);');
o('    }');
o('  };');
o('');
o('  const handleEvolve = async () => {');
o('    if (busy) return;');
o('    const prompt = input.trim() || "Evolve to better serve the user based on current context";');
o('    setInput("");');
o('    setLastResponse("Evolving...");');
o('    await self.evolve(prompt);');
o('    setLastResponse("Evolved. New form is live.");');
o('  };');
o('');
o('  if (!isOpen) {');
o('    return (');
o('      <div onClick={() => setIsOpen(true)} title="Agent Tools (think / evolve)"');
o('        style={{');
o('          position: "fixed", bottom: 20, right: 20, zIndex: 9999,');
o('          width: 44, height: 44, borderRadius: "50%",');
o('          background: busy ? "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)" : "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",');
o('          color: "#fff", fontSize: 18, cursor: "pointer",');
o('          boxShadow: "0 2px 12px rgba(0,0,0,0.25)",');
o('          display: "flex", alignItems: "center", justifyContent: "center",');
o('          transition: "all 0.3s ease", opacity: busy ? 1 : 0.7,');
o('        }}>');
o('        {busy ? "\\u2026" : "\\u2726"}');
o('      </div>');
o('    );');
o('  }');
o('');
o('  return (');
o('    <div style={{');
o('      position: "fixed", bottom: 16, right: 16, left: 16, zIndex: 9999,');
o('      background: "#fff", borderRadius: 14,');
o('      boxShadow: "0 4px 24px rgba(0,0,0,0.15)", border: "1px solid #e0e0e0",');
o('      padding: 12, maxWidth: 480, marginLeft: "auto",');
o('    }}>');
o('      {lastResponse && (');
o('        <div style={{ padding: "8px 12px", marginBottom: 8, background: "#f8f8f8", borderRadius: 8, fontSize: 13, lineHeight: 1.5, maxHeight: 150, overflowY: "auto", whiteSpace: "pre-wrap", color: "#333" }}>');
o('          {lastResponse}');
o('        </div>');
o('      )}');
o('      <div style={{ display: "flex", gap: 8, alignItems: "center" }}>');
o('        <div onClick={() => { setIsOpen(false); setLastResponse(null); }} style={{ cursor: "pointer", fontSize: 18, color: "#999", padding: "0 4px", lineHeight: 1, userSelect: "none" }}>\\u00d7</div>');
o('        <input value={input} onChange={e => setInput(e.target.value)}');
o('          onKeyDown={e => { if (e.key === "Enter") handleThink(); }}');
o('          placeholder={busy ? (self.isThinking ? "Thinking..." : "Evolving...") : "Think or evolve..."}');
o('          disabled={busy}');
o('          style={{ flex: 1, padding: "8px 12px", fontSize: 14, fontFamily: "inherit", border: "2px solid #e0e0e0", borderRadius: 8, outline: "none" }} />');
o('        <div onClick={handleThink} style={{');
o('          padding: "8px 14px", fontSize: 13, fontWeight: 600,');
o('          background: (!input.trim() || busy) ? "#ccc" : "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",');
o('          color: "#fff", borderRadius: 8, cursor: (!input.trim() || busy) ? "default" : "pointer", whiteSpace: "nowrap", userSelect: "none",');
o('        }}>Think</div>');
o('        <div onClick={handleEvolve} style={{');
o('          padding: "8px 14px", fontSize: 13, fontWeight: 600,');
o('          background: busy ? "#ccc" : "#f0f0f0", color: busy ? "#999" : "#555",');
o('          borderRadius: 8, cursor: busy ? "default" : "pointer", whiteSpace: "nowrap", userSelect: "none",');
o('        }}>Evolve</div>');
o('      </div>');
o('    </div>');
o('  );');
o('}');
o('');
o('export function AgentMount({ agentPath = "/src/agent.tsx" }: { agentPath?: string }) {');
o('  let AgentBody = window.__RUNTIME__.AgentModule?.default;');
o('  const [state, act] = useAgentState();');
o('  const self = useAgentSelf(agentPath);');
o('');
o('  const handleError = useCallback((error: Error) => {');
o('    act({ _lastError: error.message, _lastErrorTime: Date.now() });');
o('  }, [act]);');
o('');
o('  if (!AgentBody) {');
o('    return <div style={{ padding: 32, textAlign: "center", color: "#666" }}>Loading agent...</div>;');
o('  }');
o('');
o('  return (');
o('    <>');
o('      <AgentErrorBoundary onError={handleError}>');
o('        <AgentBody state={state} act={act} self={self} />');
o('      </AgentErrorBoundary>');
o('      <AgentToolbar self={self} act={act} />');
o('    </>');
o('  );');
o('}');

export const SEED_AGENT_MOUNT_SOURCE = L.join("\n");